### ISSUE TITLE
Transformar a TXTMemo

### ISSUE THREAD

**Issue by inacioMattos** [inacioMattos/identador--pascal#8]
Precisamos de ideias e maneiras para adicionar um contador de linhas no Memo e um texto placeholder no mesmo. @JoaoFGuinguer você pode enviar prints para cá com as suas ideias? E @CassiusFreitas precisamos de ideia para design, alguma?

**Comment by JoaoFGuinguer** [comment]
![print1](https://user-images.githubusercontent.com/31196344/29547481-942061a4-86d0-11e7-8a23-2377d0000f0f.png)
![print2](https://user-images.githubusercontent.com/31196344/29547482-9421134c-86d0-11e7-8a0e-7d6b576a88e3.jpg)

**Comment by JoaoFGuinguer** [comment]
Particularmente eu prefiro a segunda, mas tanto uma quanto a outra precisam de melhorias.

**Comment by CassiusFreitas** [comment]
Em minha opinião o segundo exemplo está mais bonito e atraente para os usuários.
Att.

**Comment by CassiusFreitas** [comment]
Gostaria de sugestionar uma mudança no button  "identar!!", talvez um objeto pudesse ser mais interessante. 
►

**Comment by inacioMattos** [comment]
@CassiusFreitas Abra um ticket de issue novo para isso, acho que fica mais tranquilo de organizar desta maneira. 😃

**Comment by JoaoFGuinguer** [comment]
Achei a ideia interessante, irei dar uma olhada para colocar.

**Comment by inacioMattos** [comment]
E, pensei em um modelo similar a esse (para a questão da contagem de linhas):
![screenshot_11](https://user-images.githubusercontent.com/24547963/29547601-791b071e-86d1-11e7-9598-d52fcb13b562.png)

**Comment by JoaoFGuinguer** [comment]
@inacioMattos Gostei da ideia, principalmente se houver algo indicando em que linha o usuário está editando

**Comment by inacioMattos** [comment]
@JoaoFGuinguer apesar de concordar, não creio ser algo vital ou algo que devemos gastar tempo de produção no atual momento, talvez deixarmos isso para o futuro seja a opção mais sábia. O que realmente penso ser vital para o funcionamento e beleza é acertarmos a fonte, as cores e o espaçamento entre a contagem de linha e o Memo. @CassiusFreitas Opiniões?

**Comment by CassiusFreitas** [comment]
Achei bonito, devemos analisar! 
Exemplos em foto são sempre bem vindo!
