### ISSUE TITLE
Alteração no visual

### ISSUE THREAD

**Issue by CassiusFreitas** [inacioMattos/identador--pascal#9]
Sugestão de ideia para button de execução.
ao invés de utilizarmos um botão preenchido com letras poderíamos usar um objeto (um triangulo por exemplo ou uma engrenagem).
![forma-preta-engrenagem_318-50714](https://user-images.githubusercontent.com/31196372/29548015-154609c0-86d4-11e7-89ca-2ee2733ca0d6.jpg)

**Comment by CassiusFreitas** [comment]
@inacioMattos @JoaoFGuinguer (esqueci de marcar ambos)

**Comment by JoaoFGuinguer** [comment]
Acho a ideia legal, veremos a possibilidade de ser feito.

**Comment by inacioMattos** [comment]
Não tenho certeza se seria algo que agregasse tanto valor assim. Um button padrão do Lazarus, sem dúvidas não é o ideal, contudo, criarmos nosso próprio button não é uma tarefa fácil.

Att, Inácio.
